// <auto-generated />
namespace Pantelejci_1._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DodatEnumStatusUtakmice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodatEnumStatusUtakmice));
        
        string IMigrationMetadata.Id
        {
            get { return "201707240947175_DodatEnumStatusUtakmice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
